### ISSUE TITLE
Indentation of Groups

### ISSUE THREAD

**Issue by JP-Ellis** [antonj/scss-mode#23]
Hi,

Just wanted to point out that scss-mode doesn't seem to correctly indent groups of related css properties. For example consider the following code with the correct indentation:

``` SCSS
body {
    background: {
        image: url(images/bg.jpg);
        size: cover;
        attachment: fixed;
    }
}
```

Selecting it all and then applying the scss-mode indentation changes it to:

``` SCSS
body {
    background: {
    image: url(images/bg.jpg);
    size: cover;
    attachment: fixed;
}
}
```

which you can see is not exactly desired.
