### ISSUE TITLE
Weird parenthess indentation

### ISSUE THREAD

**Issue by PythonNut** [antonj/scss-mode#25]
`scss-mode` indents parentheses like this:

```
a {
  background: linear-gradient(to bottom,
                              red,
                              blue
                             );
}
```

Which is very strange.

```
a {
  background: linear-gradient(to bottom,
    red,
    blue
  );
}
```

Is more inline with general SCSS style (and coding styles that I see in the wild).

**Comment by Silex** [comment]
I discovered this comes from css-mode and only happens when `{` is on a line of its own.

**Comment by art-solopov** [comment]
@Silex I have this even when the bracket is on the previous line:

```scss
svg .node {

  a:hover, a:focus {
             text-decoration: none;
  }
}
```
