### ISSUE TITLE
Nested indentation bug when parent rule is empty

### ISSUE THREAD

**Issue by achisholm** [antonj/scss-mode#32]
An example of current indentation behaviour...
```scss
.class-name {
    // comment
    @media (min-width:500px) {
    display:inline;
}
}
```

Desired indentation...
```scss
.class-name {
    // comment
    @media (min-width:500px) {
        display:inline;
    }
}
```

This example is a nested media query but the indentation is the same for anything (classes etc.)
